_target_: survival_analysis.models.experimental.MetricLearn

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 5e-4

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

in_dim: null
hid_dim: 10
lambda1: 1.0
lambda2: 1.0
lambda3: 1.0
out_dim: 3